[package]
name = "employee-management"
version = "0.1.0"
authors = ["Alex Garland <alex.d.garland@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"
simple_logger = "1.6.0"
regex = "1.3.9"
# Test dependencies
mockall = "0.7.1"
mockall_derive = "0.7.1"
testing_logger = "0.1.1"
